server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: flight-service
          uri: lb://flight-service
          predicates:
            - Path=/flights/**
        - id: passenger-service
          uri: lb://passenger-service
          predicates:
            - Path=/passengers/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/bookings/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/